package com.julianczaja.esp_monitoring_app.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF765B00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDF93)
val md_theme_light_onPrimaryContainer = Color(0xFF241A00)
val md_theme_light_secondary = Color(0xFF626200)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE9E86F)
val md_theme_light_onSecondaryContainer = Color(0xFF1D1D00)
val md_theme_light_tertiary = Color(0xFF486549)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC9EBC7)
val md_theme_light_onTertiaryContainer = Color(0xFF05210A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFECE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7E7667)
val md_theme_light_inverseOnSurface = Color(0xFFF7F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFEDC148)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF765B00)
val md_theme_light_outlineVariant = Color(0xFFCFC5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFEDC148)
val md_theme_dark_onPrimary = Color(0xFF3E2E00)
val md_theme_dark_primaryContainer = Color(0xFF594400)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF93)
val md_theme_dark_secondary = Color(0xFFCCCC57)
val md_theme_dark_onSecondary = Color(0xFF323200)
val md_theme_dark_secondaryContainer = Color(0xFF494900)
val md_theme_dark_onSecondaryContainer = Color(0xFFE9E86F)
val md_theme_dark_tertiary = Color(0xFFAECFAC)
val md_theme_dark_onTertiary = Color(0xFF1A361E)
val md_theme_dark_tertiaryContainer = Color(0xFF314D33)
val md_theme_dark_onTertiaryContainer = Color(0xFFC9EBC7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE8E1D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE8E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC5B4)
val md_theme_dark_outline = Color(0xFF989080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E1D9)
val md_theme_dark_inversePrimary = Color(0xFF765B00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFEDC148)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF765B00)
